spring:
  datasource:
    data: classpath:db/data.sql
    driver-class-name: org.h2.Driver
    password: ''
    schema: classpath:db/h2_schema.sql
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace:


mybatis:
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/**/*.xml


logging:
  level:
    org.mybatis: debug
    java.sql: debug
    java.sql.Statement: debug
    java.sql.ResultSet: debug
    java.sql.PreparedStatement: debug
