server:
  port: 9839



spring:
  shardingsphere:
    datasource:
      names: ds0, ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:ds1
        username: sa
        password:
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:ds2
        username: sa
        password:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ds1
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

