# https
server:
  port: 443
  http:
    port: 8080

  ssl:
    enabled: true
    key-store: classpath:ssl/tomcat.keystore
    key-store-password: 12345678
    key-store-type: JKS
    key-alias: tomcat

