mybatis:
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  datasource:
    druid:
      mysql:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.12.136.105:3306/users?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: otary_321
        primary: false
      h2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password:
        primary: true
